# -*- coding: utf-8 -*-

# Flask
DEBUG = True
TESTING = False
SECRET_KEY = ''
MAX_CONTENT_LENGTH = 8 * 1024 * 1024
SECRET_KEY = 'FILL IT WITH YOUR SECRET KEY AND DO NOT SAY IT TO ANYBODY'

# Flask-Babel
BABEL_DEFAULT_LOCALE = 'en'
BABEL_DEFAULT_TIMEZONE = 'UTC'

# Flask-WTF
WTF_CSRF_ENABLED = True

# Flask-Login
SESSION_PROTECTION = 'strong'

# Flask-Mail
#MAIL_SERVER = 'localhost'
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = False
#MAIL_DEBUG = DEBUG
#MAIL_USERNAME = None
#MAIL_PASSWORD = None
MAIL_DEFAULT_SENDER = 'user@example.com'
#MAIL_MAX_EMAILS = None
#MAIL_SUPPRESS_SEND = TESTING

# Flask-Security
SECURITY_FLASH_MESSAGES = False
SECURITY_PASSWORD_HASH = 'sha256_crypt'
SECURITY_PASSWORD_SALT = '45698980848eba8674cded5678678e7d'
SECURITY_EMAIL_SENDER = MAIL_DEFAULT_SENDER

SECURITY_LOGIN_URL = '/login/'
SECURITY_LOGOUT_URL = '/logout/'
SECURITY_REGISTER_URL = '/register/'
#SECURITY_RESET_URL = '/reset/'
#SECURITY_CHANGE_URL = '/change/'
#SECURITY_CONFIRM_URL = '/confirm/'
SECURITY_POST_LOGIN_VIEW = '/'
#SECURITY_POST_LOGOUT_VIEW = '/'
#SECURITY_CONFIRM_ERROR_VIEW = None
#SECURITY_POST_REGISTER_VIEW = None
#SECURITY_POST_CONFIRM_VIEW = None
#SECURITY_POST_RESET_VIEW = None
#SECURITY_POST_CHANGE_VIEW = None
#SECURITY_UNAUTHORIZED_VIEW = None

#SECURITY_FORGOT_PASSWORD_TEMPLATE = 'security/forgot_password.html'
SECURITY_LOGIN_USER_TEMPLATE = 'security/login_user.html'
#SECURITY_REGISTER_USER_TEMPLATE = 'security/register_user.html'
#SECURITY_RESET_PASSWORD_TEMPLATE = 'security/reset_password.html'
#SECURITY_CHANGE_PASSWORD_TEMPLATE = 'security/change_password.html'
#SECURITY_SEND_CONFIRMATION_TEMPLATE = 'security/send_confirmation.html'
#SECURITY_SEND_LOGIN_TEMPLATE = 'security/send_login.html'

SECURITY_CONFIRMABLE = True
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_TRACKABLE = True
#SECURITY_PASSWORDLESS = False
SECURITY_CHANGEABLE = True

#SECURITY_EMAIL_SUBJECT_REGISTER = 'Welcome'
#SECURITY_EMAIL_SUBJECT_PASSWORDLESS = 'Login instructions'
#SECURITY_EMAIL_SUBJECT_PASSWORD_NOTICE = 'Your password has been reset'
#SECURITY_EMAIL_SUBJECT_PASSWORD_RESET = 'Password reset instructions'
#SECURITY_EMAIL_SUBJECT_PASSWORD_CHANGE_NOTICE = 'Your password has been changed'
#SECURITY_EMAIL_SUBJECT_CONFIRM = 'Please confirm your email'

#SECURITY_SEND_REGISTER_EMAIL = True
#SECURITY_SEND_PASSWORD_CHANGE_EMAIL = True
#SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL = True.
SECURITY_CONFIRM_EMAIL_WITHIN = '24 hours'
SECURITY_RESET_PASSWORD_WITHIN = '24 hours'
#SECURITY_LOGIN_WITHIN = '1 days'
#SECURITY_LOGIN_WITHOUT_CONFIRMATION = False
#SECURITY_CONFIRM_SALT = 'confirm-salt'
#SECURITY_RESET_SALT = 'reset-salt'
#SECURITY_LOGIN_SALT = 'login-salt'
#SECURITY_REMEMBER_SALT = 'remember-salt'
SECURITY_DEFAULT_REMEMBER_ME = True

# Flask-Assets
#ASSETS_DEBUG = False
ASSETS_DEBUG = True


SQLALCHEMY_ECHO=False
